// Code generated by rec, DO NOT EDIT.\n

package tk9_0

// ltok recognizes longest ASCII lexemes. Lower IDs take precedence on same length.
//
//	id   0: $
//	id   1:
//	id   2: \{
//	id   3: \}
//	id   4: ([\x00-\x08\x0e-\x1f])|[!-\x5b\x5d-\x7a\\x7e-\x7f\xff]
//	id   5: \\(u([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])|.)
//
// ID == -1 is returned when no lexeme was recognized.
func ltok(s string) (id, length int) {
	const endOfText = 0x110000
	var pos, pos0, width, width1 int
	id = -1
	var r, r1 rune
	_ = pos0
	_ = r
	_ = r1
	_ = width1
	step := func(pos int) (r rune, n int) {
		if pos < len(s) {
			return rune(s[pos]), 1
		}
		return endOfText, 0
	}
	move := func() {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
	}
	accept := func(x rune) bool {
		if r == x {
			move()
			return true
		}
		return false
	}
	_ = accept
	accept2 := func(x rune) bool {
		if r <= x {
			move()
			return true
		}
		return false
	}
	_ = accept2
	r, r1 = endOfText, endOfText
	width, width1 = 0, 0
	r, width = step(pos)
	if r != endOfText {
		r1, width1 = step(pos + width)
	}
	if accept(' ') {
		goto l17
	}
	if accept('\\') {
		goto l19
	}
	if accept('{') {
		goto l42
	}
	if accept('}') {
		goto l44
	}
	if accept2('\b') {
		goto l15
	}
	if r < '\x0e' {
		goto l8out
	}
	if accept2('\x1f') {
		goto l15
	}
l8out:
	if r < '!' {
		goto l10out
	}
	if accept2('\x7f') {
		goto l46
	}
	if accept('\u00ff') {
		goto l46
	}
l10out:
	if r == endOfText {
		goto l48
	}
	return id, length
l15:
	id, length = 4, pos
	return id, length
l17:
	id, length = 1, pos
	return id, length
l19:
	id, length = 4, pos
	if accept('u') {
		goto l25
	}
	if accept2('\t') {
		goto l40
	}
	if r < '\v' {
		goto l22out
	}
	if accept2('\U0010ffff') {
		goto l40
	}
l22out:
	return id, length
l25:
	id, length = 5, pos
	if r < '0' {
		goto l26out
	}
	if accept2('9') {
		goto l29
	}
	if r < 'A' {
		goto l26out
	}
	if accept2('F') {
		goto l29
	}
	if r < 'a' {
		goto l26out
	}
	if accept2('f') {
		goto l29
	}
l26out:
	return id, length
l29:
	if r < '0' {
		goto l29out
	}
	if accept2('9') {
		goto l32
	}
	if r < 'A' {
		goto l29out
	}
	if accept2('F') {
		goto l32
	}
	if r < 'a' {
		goto l29out
	}
	if accept2('f') {
		goto l32
	}
l29out:
	return id, length
l32:
	if r < '0' {
		goto l32out
	}
	if accept2('9') {
		goto l35
	}
	if r < 'A' {
		goto l32out
	}
	if accept2('F') {
		goto l35
	}
	if r < 'a' {
		goto l32out
	}
	if accept2('f') {
		goto l35
	}
l32out:
	return id, length
l35:
	if r < '0' {
		goto l35out
	}
	if accept2('9') {
		goto l38
	}
	if r < 'A' {
		goto l35out
	}
	if accept2('F') {
		goto l38
	}
	if r < 'a' {
		goto l35out
	}
	if accept2('f') {
		goto l38
	}
l35out:
	return id, length
l38:
	id, length = 5, pos
	return id, length
l40:
	id, length = 5, pos
	return id, length
l42:
	id, length = 2, pos
	return id, length
l44:
	id, length = 3, pos
	return id, length
l46:
	id, length = 4, pos
	return id, length
l48:
	id, length = 0, pos
	return id, length
}
