// Copyright 2024 The tk9.0-go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build ignore

// Tcl list token grammar.
//
// https://github.com/tcltk/tcl/blob/7532f625dd115d13de41c9e696cdf6f1124b270c/generic/tclUtil.c#L157
package main

import (
	"bytes"
	"fmt"
	"os"
	"sort"

	"modernc.org/egg/lib"
	"modernc.org/rec/lib"
)

const (
	ebnf = `
List = { Element } .
Element = String | BracedString .
String = Char { Char | '{' | '}' } .
BracedString = '{' { Char | '{' | ' ' } '}' .
Char = ascii | escape_seq .
non_printable = ` + "`" + `[\x00-\x08\x0e-\x1f]` + "`" + ` .
ascii = non_printable | ` + "`" + `[!-\x5b\x5d-\x7a\\x7e-\x7f\xff]` + "`" + ` .
escape_seq = '\\' ( 'u' h h h h | ` + "`.`" + ` ) .
h = ` + "`" + `[0-9A-Fa-f]` + "`" + ` .
# white_space = { '\t' | '\n' | '\v' | '\f' | '\r' | ' ' } .
`
)

func main() {
	fmt.Println(ebnf)
	src, err := egg.NewSource("tcl.ebnf", map[string]struct{}{"List": {}}, []byte(ebnf))
	if err != nil {
		panic(err.Error())
	}

	var a []string
	for k := range src.AST.Lexicon {
		if k != "white_space" {
			a = append(a, k)
		}
	}
	sort.Strings(a)
	args := []string{"-lexstring", "ltok", "$"}
	for _, v := range a {
		args = append(args, src.AST.Lexicon[v])
	}
	var stdout, stderr bytes.Buffer
	rc, err := rec.Main(args, &stdout, &stderr)
	if err != nil {
		panic(fmt.Errorf("rc=%v err=%v stderr=%s\nstdout=%s\n", rc, err, stderr.Bytes(), stdout.Bytes()))
	}

	var b bytes.Buffer
	b.WriteString(`// Code generated by rec, DO NOT EDIT.\n

package tk9_0

`)
	b.Write(stdout.Bytes())
	if err := os.WriteFile("ltoken.go", b.Bytes(), 0600); err != nil {
		panic(err.Error())
	}
}
